### ISSUE TITLE
Playbook with roles - roles are not validated?

### ISSUE THREAD

**Issue by justinc1** [xlab-steampunk/steampunk-scanner-cli#3]
```
cat play2.yml 
- hosts: MDC
  remote_user: root
  roles:
   - first_reboot
```

```
steampunk-scanner scan --playbooks play2.yml
# no output, like everything would be OK.
```

It didn't detect there was no `roles/first_reboot` directory. Also if the role was present, it was not validated.
